version: "3"
services:
  reverse-proxy:
    image: traefik:v2.4
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - 80:80
      - 8080:8080
    networks:
      - youtube_clone
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  mariaDB:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
      - youtube_clone
    volumes:
      - mariaDB_volume:/var/lib/mysql
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "true"
      MARIADB_RANDOM_ROOT_PASSWORD: "1"
      MARIADB_DATABASE: phoenix
      MARIADB_USER: phoenix
      MARIADB_PASSWORD: phoenix

  phoenix:
    build:
      context: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phoenix.rule=host(`phoenix.localhost`)"
      - "traefik.http.routers.phoenix.entrypoints=web"
    environment:
      MARIADB_USER: phoenix
      MARIADB_PASSWORD: phoenix
      MARIADB_DATABASE: phoenix
      MARIADB_HOST: mariaDB
      DISK1: 'disk1'
      DISK2: 'disk2'
    ports:
      - 4000:4000
    expose:
      - 4000
    networks:
      - youtube_clone
    depends_on:
      - mariaDB
    volumes:
      - ./disk1:/disk1
      - ./disk2:/disk2
      - .:/app

volumes:
  mariaDB_volume:

networks:
  youtube_clone:
