version: "3"
services:
    mariaDB:
        image: mariadb
        restart: always
        ports:
          - 3306:3306
        volumes:
          - mariaDB_volume:/var/lib/mysql
        environment:
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "true"
          MARIADB_RANDOM_ROOT_PASSWORD: "1"
          MARIADB_DATABASE: phoenix
          MARIADB_USER: phoenix
          MARIADB_PASSWORD: phoenix

volumes:
  mariaDB_volume:
